// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ifs/db.go

// Package mocks is a generated GoMock package.
package mocks

import (
	repository "orgStruct/internal/repository"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDb is a mock of Db interface.
type MockDb struct {
	ctrl     *gomock.Controller
	recorder *MockDbMockRecorder
}

// MockDbMockRecorder is the mock recorder for MockDb.
type MockDbMockRecorder struct {
	mock *MockDb
}

// NewMockDb creates a new mock instance.
func NewMockDb(ctrl *gomock.Controller) *MockDb {
	mock := &MockDb{ctrl: ctrl}
	mock.recorder = &MockDbMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDb) EXPECT() *MockDbMockRecorder {
	return m.recorder
}

// InsertDepartment mocks base method.
func (m *MockDb) InsertDepartment(Depart repository.Department) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InsertDepartment", Depart)
}

// InsertDepartment indicates an expected call of InsertDepartment.
func (mr *MockDbMockRecorder) InsertDepartment(Depart interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDepartment", reflect.TypeOf((*MockDb)(nil).InsertDepartment), Depart)
}

// InsertEmployee mocks base method.
func (m *MockDb) InsertEmployee(Emplo repository.Employee) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InsertEmployee", Emplo)
}

// InsertEmployee indicates an expected call of InsertEmployee.
func (mr *MockDbMockRecorder) InsertEmployee(Emplo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEmployee", reflect.TypeOf((*MockDb)(nil).InsertEmployee), Emplo)
}

// SelectDepartmentById mocks base method.
func (m *MockDb) SelectDepartmentById(id int) (repository.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectDepartmentById", id)
	ret0, _ := ret[0].(repository.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectDepartmentById indicates an expected call of SelectDepartmentById.
func (mr *MockDbMockRecorder) SelectDepartmentById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectDepartmentById", reflect.TypeOf((*MockDb)(nil).SelectDepartmentById), id)
}

// SelectDepartmentWhereParentID mocks base method.
func (m *MockDb) SelectDepartmentWhereParentID(ParentID *int) ([]repository.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectDepartmentWhereParentID", ParentID)
	ret0, _ := ret[0].([]repository.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectDepartmentWhereParentID indicates an expected call of SelectDepartmentWhereParentID.
func (mr *MockDbMockRecorder) SelectDepartmentWhereParentID(ParentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectDepartmentWhereParentID", reflect.TypeOf((*MockDb)(nil).SelectDepartmentWhereParentID), ParentID)
}

// SelectEmployeeWhereDepartmentId mocks base method.
func (m *MockDb) SelectEmployeeWhereDepartmentId(DepartmentId int) ([]repository.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectEmployeeWhereDepartmentId", DepartmentId)
	ret0, _ := ret[0].([]repository.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectEmployeeWhereDepartmentId indicates an expected call of SelectEmployeeWhereDepartmentId.
func (mr *MockDbMockRecorder) SelectEmployeeWhereDepartmentId(DepartmentId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectEmployeeWhereDepartmentId", reflect.TypeOf((*MockDb)(nil).SelectEmployeeWhereDepartmentId), DepartmentId)
}
